### PR TITLE
chore: card-flip

### PR DESCRIPTION
**Pull request by HubertKwiatkowski**
there's probably a better/easier way to do the flip...

### CODE REVIEW

**Comment by HubertKwiatkowski** [comment]
I will be slowly migrating to js-generated HTML with each chore

**Review by Sumick — CHANGES_REQUESTED** [review]
One important thing - we should not use `innerHTML`. This makes your app vulnerable to XSS attacks, and it is a very slow method. We should build our components using JS only, as making components from strings is not maintainable at all. https://www.dhairyashah.dev/posts/why-innerhtml-is-a-bad-idea-and-how-to-avoid-it/

**Review by Sumick — CHANGES_REQUESTED** [review]
Almost there! I found one issue regarding flip. It looks like it automatically flips on app start. https://jmp.sh/IE8eA30g

**Review by Sumick — APPROVED** [review]
Looks good!

**Pull request merged**
